//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stations
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int SomeProp1 { get; set; }
        public int SomeProp2 { get; set; }
        public Nullable<int> UndergroundLine_Id { get; set; }
    
        public virtual UndergroundLines UndergroundLines { get; set; }
    }
}
